/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.2.0   2019-07-25

The MIT License (MIT)
Copyright (c) 2018 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm32f0xx.h"

// Declare private functions

void init_timer6(void);
void TIM6_IRQHandler(void);
void init_LED(void);
void CountUp();
void CountDown();
void init_buttons();
void init_EXTI(void);
void EXTI0_1_IRQHandler(void);
void init_PWM(void);
void init_ADC(void);
void run_ADC(void);

// Declare global variables

char value = 0;
char flag = 0;
char ADC_value = 0;
float fduty = 0.0;
char duty = 0;

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
int main(void)
{
	// Initialise Timer



	init_timer6();
	init_LED();
	init_buttons();
	init_EXTI();	// Note that enabling the ADC turns off the EXTI interrupt for PA2.
	init_PWM();
	init_ADC();		// Turn off ADC before trying to trigger PA2 interrupt

	while(1)
	{

		run_ADC();

		fduty = (ADC_value/(255.0) * 100.0); //((ADC_value / 255) * 100);
		duty = (int)fduty;

		// Duty cycle switches between red and green by POT 0
		TIM2->CCR3 =  duty* 40;
		TIM2->CCR4 = (100-duty) * 40;

	}
}


// Function definitions

void run_ADC(void)
{
	ADC1 -> CR |= ADC_CR_ADSTART;
	while((ADC1->ISR & ADC_ISR_EOC) == 0);

	ADC_value = ADC1->DR;
}

// Code enables PA5 - POT0.
void init_ADC(void)
{
	RCC -> AHBENR |= RCC_AHBENR_GPIOAEN;
	GPIOA -> MODER |= GPIO_MODER_MODER5;
	RCC -> APB2ENR |= RCC_APB2ENR_ADCEN;

	ADC1 -> CFGR1 |= ADC_CFGR1_RES_1;
	ADC1 -> CFGR1 &= ~ADC_CFGR1_ALIGN;
	ADC1 -> CFGR1 &= ~ADC_CFGR1_CONT;
	ADC1 -> CHSELR |= ADC_CHSELR_CHSEL5;

	ADC1 -> CR |= ADC_CR_ADEN;
	while((ADC1->ISR & ADC_ISR_ADRDY) == 0);
}

void ResetClockTo48Mhz(void)									   //COMPULSORY
{																   //COMPULSORY
	if ((RCC->CFGR & RCC_CFGR_SWS) == RCC_CFGR_SWS_PLL)			   //COMPULSORY
	{															   //COMPULSORY
		RCC->CFGR &= (uint32_t) (~RCC_CFGR_SW);					   //COMPULSORY
		while ((RCC->CFGR & RCC_CFGR_SWS) != RCC_CFGR_SWS_HSI);	   //COMPULSORY
	}															   //COMPULSORY

	RCC->CR &= (uint32_t)(~RCC_CR_PLLON);						   //COMPULSORY
	while ((RCC->CR & RCC_CR_PLLRDY) != 0);						   //COMPULSORY
	RCC->CFGR = ((RCC->CFGR & (~0x003C0000)) | 0x00280000);		   //COMPULSORY
	RCC->CR |= RCC_CR_PLLON;									   //COMPULSORY
	while ((RCC->CR & RCC_CR_PLLRDY) == 0);						   //COMPULSORY
	RCC->CFGR |= (uint32_t) (RCC_CFGR_SW_PLL);					   //COMPULSORY
	while ((RCC->CFGR & RCC_CFGR_SWS) != RCC_CFGR_SWS_PLL);		   //COMPULSORY
}

// Initiates PWM for LED's on D9
void init_PWM(void)
{
	RCC->AHBENR |= RCC_AHBENR_GPIOBEN;
	RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;
	GPIOB->MODER |= GPIO_MODER_MODER10_1;
	GPIOB->MODER |= GPIO_MODER_MODER11_1;
	GPIOB->AFR[1] |= (2 << (4*(10-8)));
	GPIOB->AFR[1] |= (2 << (4*(11-8)));

	TIM2->ARR=3999;
	TIM2->CCMR2 |= (TIM_CCMR2_OC3M_2|TIM_CCMR2_OC3M_1);
	TIM2->CCMR2 |= (TIM_CCMR2_OC4M_2|TIM_CCMR2_OC4M_1);
	TIM2->CCR3 = 50 * 40;
	TIM2->CCR4 = 50 * 40;

	TIM2->CCER |= TIM_CCER_CC3E;
	TIM2->CCER |= TIM_CCER_CC4E;

	TIM2->CR1 |= TIM_CR1_CEN;
}

void init_EXTI()
{
	RCC->APB2ENR |= RCC_APB2ENR_SYSCFGCOMPEN;	// ENABLE EXTI BUS CLK
	SYSCFG->EXTICR[0] |= SYSCFG_EXTICR1_EXTI2_PA;	// Map interruption to PA2
	EXTI->IMR |= EXTI_IMR_MR2;	//
	EXTI->FTSR |= EXTI_FTSR_TR2;
	NVIC_EnableIRQ(EXTI2_3_IRQn);
}

void EXTI2_3_IRQHandler(void)
{
	EXTI->PR |= EXTI_PR_PR2; // EXIT INTERRUPT
	asm("nop");
}

void init_buttons()
{
	// Init buttons
	RCC->AHBENR |= RCC_AHBENR_GPIOAEN;

	// Init Switch 0
	GPIOA->MODER &= ~GPIO_MODER_MODER0;
	GPIOA->PUPDR |= GPIO_PUPDR_PUPDR0_0;

	// Init Switch 1
	GPIOA->MODER &= ~GPIO_MODER_MODER1;
	GPIOA->PUPDR |= GPIO_PUPDR_PUPDR1_0;
}

void init_timer6()
{
    RCC->APB1ENR |= RCC_APB1ENR_TIM6EN; // Enable clock to timer

    TIM6->PSC = 99;   // 99
    TIM6->ARR = 240000;   // 240000

    TIM6->DIER |= TIM_DIER_UIE; // Enable interrupts on update events
    TIM6->CR1 |= TIM_CR1_CEN;

    NVIC_EnableIRQ(TIM6_IRQn);
}

void TIM6_IRQHandler()
{
    TIM6->SR &= ~TIM_SR_UIF;

    // Check if SW0 is held down then switch settings
    if ((GPIOA->IDR & GPIO_IDR_0) == 0)
    {
        TIM6->PSC = 300;   // 99
        TIM6->ARR = 240000;   // 240000
    } else {
        TIM6->PSC = 99;   // 99
        TIM6->ARR = 240000;   // 240000
    }

    if ((GPIOA->IDR & GPIO_IDR_1) == 0)
    {
    	if (flag)
    	{
    		value = 170;
    		flag = 0;
    	} else {
    		value = 85;
    		flag = 1;
    	}
    }

    CountUp();
}

void init_LED()
{
    //Initialize the LED's to be used to output data

    RCC  ->AHBENR |= 1<<18;             // Connecting GPIO Port B to the clock through the bus using bit 18
    GPIOB->MODER  |= 0x00005555;        // Setting modes of the LED's to outputs
}

void CountUp()
{
    GPIOB->ODR = value;                 // Display the current value on the LED's
    if(value == 255)                    // Check whether the value is at 255 and if it is reset it to 0
    {
        value = 0;
    }
    else                                // If value is not 255 then add 1 to the value
    {
        value += 1;
    }
}
